### ISSUE TITLE
Can't install packages from requirements.txt

### ISSUE THREAD

**Issue by abhatthal** [CSSS/wall_e#230] opened 2019-09-15 19:27 UTC
I installed python3.5 and ran get-pip with it, on MacOS.
I run `python3.5 -m pip install -r requirements.txt`
I get the error:

> Collecting yarl<1.2 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement yarl<1.2 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for yarl<1.2 (from -r requirements.txt (line 1))
(ENV)

So I try
`python3.5 -m pip install requirements.txt``pip3 install -r requirements.txt`
`pip3 install requirements.txt`
and simply
`pip3 install yarl`
Even by not specifying the version, this issue is persistent.
I even tried installing other packages which work typically, such as requests, and they return a similar error.  Since pip3 isn't working for any packages, I think there may be an issue with the get-pip script itself.

**Comment by abhatthal** [comment] 2019-09-15 19:34
Interestingly enough, this works with pip3.7 for python3.7.  And by running pip3.7 install discord,
I end up installing yarl, aiohttp, websockets, etc..
So this furthers my suspicion that it's just the get-pip script for pip3.5 that wasn't working right.

**Comment by abhatthal** [comment] 2019-09-15 19:49
I ran get-pip again and then from that same directory ran
`python3.5 -m pip install -r wall_e/requirements.txt`
which installed yarl successfully (yay!)
however, gave me this error for psycopg2
> `Collecting psycopg2 (from -r wall_e/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/5c/1c/6997288da181277a0c29bc39a5f9143ff20b8c99f2a7d059cfb55163e165/psycopg2-2.8.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/kash/Projects/wall_e/ENV/bin/python3.5 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/v3/vh3z1m395cqdcpsgr_s8ms4r0000gn/T/pip-install-j_q_j057/psycopg2/setup.py'"'"'; __file__='"'"'/private/var/folders/v3/vh3z1m395cqdcpsgr_s8ms4r0000gn/T/pip-install-j_q_j057/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/v3/vh3z1m395cqdcpsgr_s8ms4r0000gn/T/pip-install-j_q_j057/psycopg2/
    Complete output (27 lines):
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(ENV) ------------------------------------------------------------`

**Comment by abhatthal** [comment] 2019-09-15 19:54
Solution to that error: Run `pip3.5 install psycopg2-binary`, remove psycopg2 from requirements.txt
Run ` I run python3.5 -m pip install -r wall_e/requirements.txt`

**Comment by abhatthal** [comment] 2019-09-15 20:03
Requirements for aiohttp version couldn't be met, so install without version specification.
`python3.5 -m pip install aiohttp`
`python3.5 -m pip install discord==0.16.12`
`python3.5 -m pip install pytz`

2019-09-15 13:01:52 = WARNING - [Errno 2] No such file or directory: '/Users/kash/Projects/wall_e/logs/2019_09_15_13_01_52_wall_e.log'

`mkdir logs`
`python3.5 main.py`

AAAND now it's online, god that was a pain.

**Comment by abhatthal** [comment] 2019-09-15 20:10
Alright, so pip3.5 literally cannot find a version of discord > 0.16.12, so I'm stuck on async.  Even though the bot runs, literally none of the commands work, so I can't really test anything..

**Comment by modernNeo** [comment] 2019-09-15 20:27
will try on my machine after this week to see what the issue is.

**Comment by abhatthal** [comment] 2019-09-15 21:08
`pip3.5 install -U 'yarl<1.2'`
`pip3.5 uninstall discord`
`pip3.5 install -U 'git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]'`
then wait an eternity for a giant installation...then it fails...
`pip3.5 install telepot`
`pip3.5 install aiohttp==3.0.0b0`
Now try again...
`pip3.5 install -U 'git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]'`
wait for forever...and it fails for aiohttp not being recent enough..

I try Python 3.7, since 3.5 is being dumb
`python3.7 -m pip install -r requirements.txt`

Ran it, now the bot generates a log in my test server called #localhost_nodb_logs
And otherwise states that it's unable to load commands.
I tried reinstalling aiohttp and going back and forth between py3.5 and 3.7, commands refuse to load, and occasional warnings about things not being awaited.

**Comment by modernNeo** [comment] 2019-09-24 03:02
this whole thing will be moving to a container based system on the next merge to master. so there will no longer be any need to mess around with the requirements as long as you can use docker

**Closed by modernNeo** 2019-09-24 03:02 UTC

**Comment by modernNeo** [comment] 2019-12-26 06:37
just wanted to let you know that the revamp I promised is now here as PR https://github.com/CSSS/wall_e/pull/234 is now merged and working. the steps for developing wall_e on any computer that can use `docker` and `docker-compose` should now work.
