### ISSUE TITLE
Embeds do not validate length of contents

### ISSUE THREAD

**Issue by wnfldchen** [CSSS/wall_e#142] opened 2018-11-14 08:27 UTC
```
2018-11-14 08:06:03 = WARNING - discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
In embed.fields.0.value: Must be 1024 or fewer in length.
```
[Link to log here.](https://discordapp.com/channels/465036366699429888/488482783971377164/512181088894976000)
A fix would be to change embed.py to perform input validation and truncate fields which are too long. A list of field lengths are [here](https://discordapp.com/developers/docs/resources/channel#embed-limits).

**Comment by modernNeo** [comment] 2019-02-15 22:47
Issue going on here is when a Minion calls the embed function with inputs where a name or value field exceeds the length set out in the link that Winfield linked above. example like so
`.em asdfasdfadfasdfasdfasdfadfasdfasdfadfasdfadsfadsfadsfasdfasdfasdfasdfasdfadsfasdfadfadfadfadsfadsfadfadsfadsfadfadsfadsfadfasdfadsfadfadfadsfasdfadfasdfadfasdfadsfasdfasdfadsfasdfasdfasdfadsfadfasdfadsfadsfasdfadsfadfadfasdfadsfadfadsfadsfadsfadfadsfadsfadsfadfafdadfasdfasdfadsf a` where the first part of the string gets added to the `name` field but is too big (with a length of 280)
this part of the code is the issue.
https://github.com/CSSS/wall_e/blob/a51e99b81eb9e0db2a8d44d1cc0de92adfbdc3c1/helper_files/embed.py#L27-L28

the following check  needs to be added before  
	
	for record in content:
		if record[0].length() > 256:
			ctx.send("length of name ["+str(record[0])+"] being added to the name field is "+str(record[0].length-256)+" too big, pleae cut down to a size of 256")
			logger.info("[Mod embed()] length of name ["+str(record[0])+"] being added to the field is too big")
			return false
		if record[1].length() > 1024:
			ctx.send("length of name ["+str(record[1])+"] being added to the name field is "+str(record[0].length-1024)+" too big, pleae cut down to a size of 1024")
			logger.info("[Mod embed()] length of name ["+str(record[1])+"] being added to the field is too big")
			return false

which means that here https://github.com/CSSS/wall_e/blob/a51e99b81eb9e0db2a8d44d1cc0de92adfbdc3c1/commands_to_load/Mod.py#L57-L58

there should be a check to see if the embed was successfully done, like so:

	
	eObj = em(description=desc, author=name, avatar=ctx.author.avatar_url, colour=0xffc61d ,content=fields)
	if eObj is not False:
		await ctx.send(embed=eObj)
	else:
		await ctx.send("[Mod embed()] issue detected wth embed function, please look above for what the issue is.")

**Comment by modernNeo** [comment] 2019-03-23 03:43
being fixed with PR https://github.com/CSSS/wall_e/pull/182

**Closed** 2019-03-28 07:55 UTC
Labels: PR-created, bug
